### ISSUE TITLE
Weighbridge App Changes

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#10]
1. Bring Order Line before Payment Rule. According to Order all the fields should be filled from Payment to price
2. Hide Billing Name for Order Line
3. Delivered qty should be ZERO ( Deliveryed Qty so far)
4. Order line should capture phone for Site Supervisor (This number will be used to sending challan)
5. Vehicle Rent (Lumpsump / MT) 
6. In Order, It should not ask primary DC for secondary weight
7. In New trip, one popup window required to pick primary dc (cash,credit or order based) to create secondary entry easily.

Whatsapp invoice to Business Partner Phone
DC to OrderLine phone number

Delivered qty vs TP weight vs Invoiced Qty Report is required.

**Comment by balamuruugan** [comment]
1. Customer is mandatory for credit payment rule (Don't allow new customer for credit). Customer & Phone no are mandatory for cash payment rule. 
2. Change Delivery qty to Delivered qty so far
3. Add Delivery Contact in DC Report. If Delivery Contact is blank, show customer contact
4.

**Comment by syvasoft** [comment]
Have one more new field in the weighment entry as driver phone number..
it should be fetched from TP csv file.
