### ISSUE TITLE
Common Transporter between the Company and the Customer

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#142]
Have **Customer's Transporter** Checkbox
in Order Line, Dispatch LIne and Weighment Entry

if it is selected then the Transporter Material Receipt should not be created. and shipment line for the vehicle.

All the freight related validation should be applicable only if this checkbox is not selected.

**Comment by syvasoft** [comment]
It should work like a customer vehicle when this checkbox selected.

**Comment by veerar96** [comment]
Fixed
