### ISSUE TITLE
Price confidancial scenarios shows the freight UOM error

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#143]
Price confidential scenarios shows the freight UOM error
with freight exclusive created the order.

if try to complete the weighment entry shows the freight UOM field is mandatory but not shows this field.

![image](https://user-images.githubusercontent.com/74590393/120347036-8d784400-c319-11eb-88c3-ad95597889cc.png)

**Comment by veerar96** [comment]
Fixed
