### ISSUE TITLE
Dc w/o order scnario plan tp qty remove round off 

### ISSUE THREAD

**Issue by veerar96** [syvasofterp/org.syvasoft.fortcityminerals#145]
![f1](https://user-images.githubusercontent.com/72932511/120353772-85bb9e00-c31f-11eb-8a46-e49ed02fb05f.JPG)
![f2](https://user-images.githubusercontent.com/72932511/120353882-a126a900-c31f-11eb-82b2-1f0d9f4fbaff.JPG)
![f3](https://user-images.githubusercontent.com/72932511/120354035-c74c4900-c31f-11eb-8601-5f92be442f33.JPG)

**Comment by syvasoft** [comment]
@balamuruugan, let me know what approach we follow in to show TP balance Qty whether it is round off or as it is?
Need to confirm with Anilsoni.

**Comment by veerar96** [comment]
Fixed
