### ISSUE TITLE
If exclude the freight charge orders can't create.

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#146]
If exclude the freight charge orders can't create.
dispatch plan line also can't shows the list of freight UOM.
![image](https://user-images.githubusercontent.com/74590393/120451958-7f750280-c3af-11eb-89bb-eb8aacdad891.png)

vehicle rent config also have this product and customer same destination also but not seen the data here.

otherwise try to complete the first trip can't complete the trip. freight UOM is mandatory.

**Comment by veerar96** [comment]
Fixed

**Comment by imsabari** [comment]
Fixed.
