### ISSUE TITLE
Need to show the correct price at rate column 

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#169]
Need to show the correct price in the rate column. 

![image](https://user-images.githubusercontent.com/74590393/121765897-e0e56000-cb6b-11eb-9ab1-9ffc76f8e831.png)

![image](https://user-images.githubusercontent.com/74590393/121765898-e478e700-cb6b-11eb-9586-78e74ce1ec95.png)

**Comment by syvasoft** [comment]
While creating an invoice, all prices in the invoice line should be set as DC Price.

**Comment by imsabari** [comment]
invoice conversion issue fixed.

![image](https://user-images.githubusercontent.com/74590393/121848191-4c176980-cd07-11eb-8459-50722a66a947.png)
