### ISSUE TITLE
TP Weight should be equal or more than the Net Weight Don't allow the negative weight.

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#17]
TP Weight should be equal or more than the Net Weight,
Not in less than.
If in less than we doesn't allow to invoice the difference weight in negative.

and validate the scenario is need more than one invoice if required create or no need to create more than one.

Ref : 19/S_UMMESH CONSTRUCTION_12 MM
Inv no : 1000016 and 97 ( in online )

**Comment by syvasoft** [comment]
Create TP and Non TP Invoice for the Primary DC, TP Weight should be equal or less than the Netweight qty.
