### ISSUE TITLE
TP and Non TP invoice issue

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#172]
TP and Non TP invoice not create properly 

invoice should be create and only the avail qty.
![image](https://user-images.githubusercontent.com/74590393/121779808-28dfa380-cbbb-11eb-9edc-c4883f463c85.png)

![image](https://user-images.githubusercontent.com/74590393/121779824-372dbf80-cbbb-11eb-971f-c723e6d4d28a.png)

**Comment by syvasoft** [comment]
**These two validations are done.**
1. Secondary cannot be created as TP and Non TP.. only TP based invoice can be created.
2. TP Weight should be greater ZERO for the Secondary DC Invoice.

**Comment by syvasoft** [comment]
Here the Secondary DC Should always have TP Weight.. That's the core purpose of creating Secondary DC. So your use case is wrong. Anyway the above two validations are done to create ZERO qty invoice.

**Comment by imsabari** [comment]
Fixed

**Comment by veerar96** [comment]
Fixed
