### ISSUE TITLE
Need to validate the More than plan at Current pending order info

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#18]
Need to validate the More than planed Qty get the max of the planed qty.

is it one or more than records form current pending order window to dispatch line via schedule dispatch plan.
and validate is not empty and Zero.

**Comment by syvasoft** [comment]
Bala, better take balance qty if the plan qty is greater than balance qty

**Comment by balamuruugan** [comment]
no need to fix it.
