### ISSUE TITLE
In Weighbridge App, Freight Inlcusive and Customer's Transporter Validation

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#187]
Freight Inclusive and Customer's Transporter
either one should be selected.

**If the Customer's Transporter selected then Validate**
1. Own Vehicle should not be selected for the Customer's Transporter (show message)
2. Freight Inclusive should not be selected for the Customer's Transporter (show message)

**Comment by imsabari** [comment]
yes validation working on orders.
![image](https://user-images.githubusercontent.com/74590393/122231476-183f6e00-ced8-11eb-8da3-a83e5e1f9418.png)

![image](https://user-images.githubusercontent.com/74590393/122231663-3c9b4a80-ced8-11eb-8b79-95c17908d5ae.png)
