### ISSUE TITLE
Freight UOM is missing in Transporter DC - No Price

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#198]
![image](https://user-images.githubusercontent.com/7080552/122571509-6dab8480-d06a-11eb-9dcc-1d6fd6124ae7.png)

**Comment by veerar96** [comment]
Fixed  
![image](https://user-images.githubusercontent.com/72932511/123502447-36406780-d66a-11eb-92b0-5ef8fefd75ba.png)

**Comment by imsabari** [comment]
![image](https://user-images.githubusercontent.com/74590393/123504198-6d684600-d675-11eb-9557-3ae592c94435.png)
