### ISSUE TITLE
Second Trip Need to give the manual entry on Third Party Weibridge Scenario

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#199]
Second Trip Need to give the manual entry (weight) on Third Party Weibridge Scenario by default 

off the manual entry after try the scenario.

![image](https://user-images.githubusercontent.com/74590393/122576488-5ae77e80-d06f-11eb-9740-6bdd2bfc2285.png)

**Comment by veerar96** [comment]
Fixed

**Comment by veerar96** [comment]
Fixed

**Comment by imsabari** [comment]
By default the manual entries opened. 

![image](https://user-images.githubusercontent.com/74590393/123505057-8b847500-d67a-11eb-9c7b-c05d9dd88779.png)

**Comment by imsabari** [comment]
Not show again above issue.

Fixed.
