### ISSUE TITLE
Cash Customer Scenario  Weighbridge side payment rule Cash but Server Side payment Rule Credit  How to Possible ?

### ISSUE THREAD

**Issue by veerar96** [syvasofterp/org.syvasoft.fortcityminerals#201]
![o7](https://user-images.githubusercontent.com/72932511/122633419-40a4b380-d0f6-11eb-957b-f584b6dd626f.JPG)
![o8](https://user-images.githubusercontent.com/72932511/122633427-469a9480-d0f6-11eb-9b6e-7827923291ce.JPG)
DC No: 534/VE

**Comment by syvasoft** [comment]
It is correct. it is done as per the customer requirements
