### ISSUE TITLE
Not updated the Delivered Qty in grid

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#203]
Not updated the delivered qty in grid and the entry is uploaded in the server.

![image](https://user-images.githubusercontent.com/74590393/122646579-7751ec80-d13d-11eb-8147-890a33102f61.png)

![image](https://user-images.githubusercontent.com/74590393/122646659-e7f90900-d13d-11eb-95ab-ca2d8719c3a5.png)

[FortCity.zip](https://github.com/syvasofterp/org.syvasoft.fortcityminerals/files/6680888/FortCity.zip)

**Comment by veerar96** [comment]
Fixed

**Comment by imsabari** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/74590393/123231768-2142c780-d4f6-11eb-875b-f194b570c04b.png)
