### ISSUE TITLE
Delivered Qty need to update in Dispatch plan line

### ISSUE THREAD

**Issue by veerar96** [syvasofterp/org.syvasoft.fortcityminerals#209]
![2 1](https://user-images.githubusercontent.com/72932511/122921230-e028a700-d37f-11eb-9bb0-302d25f7af43.JPG)
![2 2](https://user-images.githubusercontent.com/72932511/122921257-e61e8800-d37f-11eb-8a5a-77ad688a821b.JPG)
![2 3](https://user-images.githubusercontent.com/72932511/122921280-ecacff80-d37f-11eb-8b9e-c023313214af.JPG)
![2 4](https://user-images.githubusercontent.com/72932511/122921309-f3d40d80-d37f-11eb-854b-7f9fc43d4131.JPG)

**Comment by imsabari** [comment]
updating 
![image](https://user-images.githubusercontent.com/74590393/123050816-b83c5080-d41e-11eb-9e6b-c3adcc73c019.png)

**Comment by veerar96** [comment]
Fixed
![Cv](https://user-images.githubusercontent.com/72932511/123058483-7fa07500-d426-11eb-9c2d-f10521a7559d.JPG)

**Comment by imsabari** [comment]
fixed
