### ISSUE TITLE
Need to hide this columns in price confidencial?

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#210]
Need to hide this columns in price confidencial.
![image](https://user-images.githubusercontent.com/74590393/123046028-3e559880-d419-11eb-8100-bed47eaeb9f9.png)

**Comment by imsabari** [comment]
fixed

**Comment by imsabari** [comment]
first trip also

![image](https://user-images.githubusercontent.com/74590393/123055748-d6587f80-d423-11eb-83de-212c8e0353f1.png)

**Comment by imsabari** [comment]
also the secondary entry.

![image](https://user-images.githubusercontent.com/74590393/123056823-e9b81a80-d424-11eb-88b3-e334c13fb86c.png)

**Comment by veerar96** [comment]
Fixed
![0 1](https://user-images.githubusercontent.com/72932511/123067905-06f1e680-d42f-11eb-8887-ba9894b790f9.JPG)
![0 2](https://user-images.githubusercontent.com/72932511/123067927-0eb18b00-d42f-11eb-86a2-817e52f42442.JPG)

**Comment by imsabari** [comment]
fixed
