### ISSUE TITLE
Need to refresh the net price if change the tax flag 

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#211]
[FortCity (3).zip](https://github.com/syvasofterp/org.syvasoft.fortcityminerals/files/6699787/FortCity.3.zip)
Need to refresh the net price if change the tax flag 

price inclusive unchecked so price also same both columns the price is 30 *150 qty =4500 now the product price is 4285.
and the final price was changed correctly and also need to show correctly.

pls check.

![image](https://user-images.githubusercontent.com/74590393/123052926-fa669180-d420-11eb-80f6-14db913d89bc.png)

**Comment by imsabari** [comment]
FIXED

**Comment by veerar96** [comment]
Fixed
