### ISSUE TITLE
Total Amount Words Mismatch

### ISSUE THREAD

**Issue by veerar96** [syvasofterp/org.syvasoft.fortcityminerals#215]
Weighbridge Report
![image](https://user-images.githubusercontent.com/72932511/123415141-7522de80-d5d2-11eb-96cc-4ad5a7577e07.png)

**Comment by syvasoft** [comment]
Royalty pass amount is missed?

**Comment by imsabari** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/74590393/123504244-a4d6f280-d675-11eb-85ab-cc70811c99cf.png)

![image](https://user-images.githubusercontent.com/74590393/123504417-d13f3e80-d676-11eb-93de-dfcdf6562d75.png)

![image](https://user-images.githubusercontent.com/74590393/123504437-f59b1b00-d676-11eb-846e-c94e29932426.png)

**Comment by veerar96** [comment]
Fixed

**Comment by imsabari** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/74590393/124075766-fced6a80-da62-11eb-86e9-a2f2e15ade99.png)

![image](https://user-images.githubusercontent.com/74590393/124075783-0080f180-da63-11eb-9498-44c9ccbf12ee.png)
