### ISSUE TITLE
Driver Beta Showing Second Screen which ones correct?

### ISSUE THREAD

**Issue by veerar96** [syvasofterp/org.syvasoft.fortcityminerals#216]
![7 3](https://user-images.githubusercontent.com/72932511/123416341-0fcfed00-d5d4-11eb-9fe8-9b63bbb6ce71.JPG)
![7 4](https://user-images.githubusercontent.com/72932511/123416363-15c5ce00-d5d4-11eb-89b1-cb410f440997.JPG)

**Comment by veerar96** [comment]
Fixed

**Comment by imsabari** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/74590393/123617222-a72b7f00-d824-11eb-96b5-86a13def984e.png)
