### ISSUE TITLE
Generating Invoice Form Dc

### ISSUE THREAD

**Issue by veerar96** [syvasofterp/org.syvasoft.fortcityminerals#217]
![image](https://user-images.githubusercontent.com/72932511/123417122-01ce9c00-d5d5-11eb-851a-731932f2bf4d.png)

**Comment by imsabari** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/74590393/123644139-b9b4b100-d842-11eb-8167-608d1a88c313.png)

**Comment by veerar96** [comment]
Fixed
