### ISSUE TITLE
After Update the TP Weight not upload the entry to server

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#220]
weighment completed and updated the TP weight after updated the entry not uploaded 
#DC - 569/SBR

![image](https://user-images.githubusercontent.com/74590393/123505492-02bb0880-d67d-11eb-87da-0aa0c6f15a74.png)

[FortCity (6).zip](https://github.com/syvasofterp/org.syvasoft.fortcityminerals/files/6719721/FortCity.6.zip)

**Comment by veerar96** [comment]
Fixed

**Comment by imsabari** [comment]
Fixed uploaded and works the void also.
