### ISSUE TITLE
Rent amount not added in the total

### ISSUE THREAD

**Issue by imsabari** [syvasofterp/org.syvasoft.fortcityminerals#243]
Rent amount not added in the total amount,

346 & 361

![image](https://user-images.githubusercontent.com/74590393/126322148-42408428-1af0-4e67-ac5c-c7d5ee48d2e1.png)

![image](https://user-images.githubusercontent.com/74590393/126322176-b362fe71-69e4-47bf-b7de-c5c25c0f0c14.png)

**Comment by syvasoft** [comment]
Due to callout, it didn't work. I have fixed it.
