### ISSUE TITLE
Freight UOM and Freight Price are mandatory for the Freight Exclusive and Own/Hired Vehicled

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#35]
Need to discuss with Anil Soni reg:
1. Do we have to enforce Frieght UOM and Price are mandatory in case of the hired/own vehicle are used to deliver the material which is not frieght Inclusive?
2. We can enforce the freight, but the customer hired vehicle on their own there will be a problem by enforcing it.

**Comment by balamuruugan** [comment]
Make it mandatory for the Transporter Vehicle if the price is freight exclusive.
