### ISSUE TITLE
After scheduling Plan from the Create Dispatch Plan, better show zoom to open the dispatch plan window

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#42]
![image](https://user-images.githubusercontent.com/7080552/117603768-7fe3fa00-b171-11eb-8441-86f8e92f576a.png)

**Comment by syvasoft** [comment]
![image](https://user-images.githubusercontent.com/7080552/117604444-051bde80-b173-11eb-8c99-92f3abb38c6b.png)
Here you can provide zoom link to open the already planned line.

**Comment by balamuruugan** [comment]
fixed
