### ISSUE TITLE
Weighment Entry based on Order Line

### ISSUE THREAD

**Issue by balamuruugan** [syvasofterp/org.syvasoft.fortcityminerals#5]
Capture Tareweight

Based on Vehicle No, populate the following fields TP No, TP Weight,& Tare Weight.. when the data is available on generated csv file

When order line is selected, 
1. Show the balance quantity (total qty of that order line - sum of actual quantity created from WE for that order)
2. Show the balance quantity (TP Weight) (total qty of that order line - sum of TP Weight created from WE for that order)

When Order line is selected, hide Primary Document field.

**Comment by syvasoft** [comment]
Have a configuration for the csv path
