### ISSUE TITLE
Transporter Invoice with/without Reverse Charges

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#71]
1. Individual DC Invoice
2. Consolidated Invoice
3. With Reverse Charges
4. Without Revers Charges

**For with Reverse Charges**
At time of purchasing such goods/ services:
Purchase A/c Dr
Input SGST A/c Dr
Input CGST Ac Dr
To Creditor A/c
To Output SGST RCM A/c
To Output CGST RCM A/c

In case of purchase of asset or expense, specific account will be debited. Output SGST RCM A/c  is used in place of normal Output SGST A/c to differentiate both taxes as taxes under RCM can not be adjusted against input taxes and has to be paid in cash.
Ref: https://taxadda.com/gst-reverse-charge-mechanism/

**Comment by syvasoft** [comment]
**Solution for Reverse Charges**
Create Tax Summary which has Four child tax
2 for input GST and other 2 for Output GST with -ve Rate.

**Comment by syvasoft** [comment]
**Update Notes:**
0. TransporterInvoice Pack in System Side
1 Pack out Transporter DC Info
2. Update Transporter DC View

**Comment by syvasoft** [comment]
Create Transporter DC
Remove Reverse Charge
Provide Tax inclusive checkbox

**Comment by syvasoft** [comment]
Create each line for the selected Transporter DCs
	
Transporter Invoice columns	
DC No
	Customer Name  and Shipmen To
	Destination - Shipment Destination
	Distance 
	Vehicle NO
	Qty
	UOM
	Price
	Amount
Tax will be 2nd row	


Show Rate MT/KM as it is only in invoice

Have transported invoice sequence separately
Invoice Name: Transporter Invoice

**Comment by syvasoft** [comment]
**Vehicle Rent Configuration**
1. Have child tab for customer margin
2. Freight Rate is charged by Vendor
3. Rent margin will be charged additionally to the customer.. This is the default margin for all customers.
4. Have Transport Order window and Order Line will be vehicle rent config.

**Comment by syvasoft** [comment]
Unknown vehicle rent config should have same UOM
and UOM Should be editable.

**Comment by syvasoft** [comment]
Transport Order is Special header-detail window to capture vehicle rent config
In Sales Activities
show Transporter Order and Transporter Invoice

**Comment by syvasoft** [comment]
Stop Trasnporter inovice creation for ZERO Price Transporter DC for all the transporters if one row has ZERO Price

**Comment by syvasoft** [comment]
Use Notice approach to track other users activity to double check their transactions accuracy.

**Comment by balamuruugan** [comment]
[01System_TransporterInvoice.zip](https://github.com/syvasofterp/org.syvasoft.fortcityminerals/files/6522386/01System_TransporterInvoice.zip)

**Comment by balamuruugan** [comment]
[02Client_TransporterInvoice.zip](https://github.com/syvasofterp/org.syvasoft.fortcityminerals/files/6522391/02Client_TransporterInvoice.zip)
