### ISSUE TITLE
Transporter Order

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#72]
https://github.com/syvasofterp/org.syvasoft.fortcityminerals/issues/71

Create Transporter Order window 
Transporter Order Line will look like a vehicle rent config.
Upon completion, rent configuration should be created with reference of the Transport Order line.

**Comment by syvasoft** [comment]
Header Table Name: TF_TOrder  (MTransportOrder)
Line Table Name; TF_TOrderLine (MTransportOrderLine)

Header Fields:
1. Org
2. Document No
3. Date Ordered
4. Business Partner (Vendor Only)
5.  Document Status
6. Processed
7. Processing (Process Now)
8. and other system fields

Order Line
1. Vehicle Type
2. Destination
3. Freight UOM
4. Feight Rate

Add new column (TF_TOrderLine_ID) into Vehicle Rent config window

While completing Transport Order, copy Transport Order lines into Vehicle Rent Config

**Comment by imsabari** [comment]
[Uploading SystemTransportOrder.zip…]()

**Comment by imsabari** [comment]
Use this Pack out also 

Transaction order reference added here.


[SystemVehicleRentConfig.zip](https://github.com/syvasofterp/org.syvasoft.fortcityminerals/files/6521098/SystemVehicleRentConfig.zip)
