### ISSUE TITLE
Transporter Order Report

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#74]

**Comment by imsabari** [comment]
**Pack out** for Transport Order Report

[SystemTransportOrderReport.zip](https://github.com/syvasofterp/org.syvasoft.fortcityminerals/files/6526264/SystemTransportOrderReport.zip)

**Comment by syvasoft** [comment]
![image](https://user-images.githubusercontent.com/7080552/119231818-4b444b00-bb40-11eb-9898-9f835c06873e.png)
Print preview is not working for the second line.

**Comment by balamuruugan** [comment]
Fixed
