### ISSUE TITLE
Document Attachment window

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#77]
Specify the voucher/document no
see the customer
attach the document.

**Comment by syvasoft** [comment]
In addition to System Fields, have the following fields in this window.
TransactionType (Use it from Sales Activities Header)
TF_WeighmentEntry_ID (Search)
C_Payment_ID (Search)
C_Invoice_ID (Search)
Description

**Comment by syvasoft** [comment]
These _ID column field should be displayed based on the transactiontype

**Comment by imsabari** [comment]
**Pack Out** for Document Attachment

[SystemDocument Attachment.zip](https://github.com/syvasofterp/org.syvasoft.fortcityminerals/files/6521025/SystemDocument.Attachment.zip)
