### ISSUE TITLE
Cash Book Entry Changes

### ISSUE THREAD

**Issue by syvasoft** [syvasofterp/org.syvasoft.fortcityminerals#87]
1. Provide DC Reference in the Customer Payment Receipt
2. Weighbridge Operator only see DC, Hide Invoice

**Comment by syvasoft** [comment]
After choosing the DC, set the description automatically

**Comment by syvasoft** [comment]
To do:
1. Add TF_WeighmentEntry_ID  to C_Payment table
2. In CalloutPayment_ElementValue, if the above weighment entry filled then show the "Payment received for <DCNo>"
3. In Cash Book Entry window, Display logic for this weighment entry field is @IsReceipt@=Y & @TF_BPartner_ID@ > 0 & @IsEmployee@=N

**Comment by syvasoft** [comment]
System Side
[CashBookDC.zip](https://github.com/syvasofterp/org.syvasoft.fortcityminerals/files/6533053/CashBookDC.zip)

**Comment by imsabari** [comment]
Tested Works good.
